import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
	return (
		<Html lang="th">
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<body style={{ background: '#cffafe' }}>
				<Main />
				<NextScript />
			</body>
		</Html>
	)
}
